---
language: python
python: "2.7"
group: deprecated-2017Q4
sudo: required
dist: trusty
services:
  - docker

before_install:
 - sudo apt-get update -qq

install:
  - sudo pip install docker-py
  - sudo apt-get install -y sshpass software-properties-common python-software-properties
  # - sudo apt-add-repository -y ppa:ansible/ansible
  # - sudo apt-get update -qq
  - sudo pip install ansible==2.2.0.0
  # - sudo apt-get install -y ansible
  - echo -e 'localhost ansible_connection=local' > tests/inventory
  - echo -e '[defaults]\nroles_path = ../\nhostfile = ./tests/inventory' > ansible.cfg
  - sudo rm /usr/bin/python && sudo ln -s /usr/bin/python2.7 /usr/bin/python
  - ansible --version

script:
  - ansible-playbook --syntax-check tests/role.yml
  - ansible-playbook -v --diff tests/role.yml
  - >
    ansible-playbook tests/role.yml
    | grep -q 'failed=0'
    && (echo 'Failed test: pass' && exit 0)
    || (echo 'Failed test: fail' && exit 1)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
